/* eslint-disable */
// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotePollIdRouteImport } from './routes/vote/$pollId'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCreatePollRouteImport } from './routes/dashboard/create-poll'

// ==== ROUTE DEFINITIONS ====

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const VotePollIdRoute = VotePollIdRouteImport.update({
  id: '/vote/$pollId',
  path: '/vote/$pollId',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardCreatePollRoute = DashboardCreatePollRouteImport.update({
  id: '/dashboard/create-poll',
  path: '/dashboard/create-poll',
  getParentRoute: () => rootRouteImport,
} as any)

// ==== INTERFACES ====

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/vote/$pollId': typeof VotePollIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/create-poll': typeof DashboardCreatePollRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/vote/$pollId': typeof VotePollIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/create-poll': typeof DashboardCreatePollRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/vote/$pollId': typeof VotePollIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/create-poll': typeof DashboardCreatePollRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/vote/$pollId'
    | '/dashboard'
    | '/dashboard/create-poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/vote/$pollId'
    | '/dashboard'
    | '/dashboard/create-poll'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/vote/$pollId'
    | '/dashboard/'
    | '/dashboard/create-poll'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VotePollIdRoute: typeof VotePollIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCreatePollRoute: typeof DashboardCreatePollRoute
}

// ==== MODULE AUGMENTATION ====

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$pollId': {
      id: '/vote/$pollId'
      path: '/vote/$pollId'
      fullPath: '/vote/$pollId'
      preLoaderRoute: typeof VotePollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/create-poll': {
      id: '/dashboard/create-poll'
      path: '/dashboard/create-poll'
      fullPath: '/dashboard/create-poll'
      preLoaderRoute: typeof DashboardCreatePollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

// ==== ROOT ROUTE TREE ====

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  LoginRoute,
  SignupRoute,
  VotePollIdRoute,
  DashboardIndexRoute,
  DashboardCreatePollRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
